In [1]:
import pandas as pd

In [2]:
claims = pd.DataFrame({
    "claim_id": ["C101", "C102", "C103", "C104", "C105", "C106", "C107", "C108"],
    "hospital": ["Apollo", "Ruby", "Apollo", "Sahyadri", "Ruby", "Apollo", "Sahyadri", "Ruby"],
    "claim_type": ["Surgery", "Emergency", "OPD", "Surgery", "Emergency", "Surgery", "OPD", "Emergency"],
    "claim_amount": [85000, 42000, 5000, 125000, 67000, 35000, 8000, 95000],
    "status": ["Approved", "Pending", "Approved", "Pending", "Rejected", "Pending", "Approved", "Pending"]
})

Find claims where:

claim_amount > 50000
AND status == "Pending"

In [3]:
claims[(claims['claim_amount'] > 50000) & (claims['status'] == 'Pending')]

  claim_id  hospital claim_type  claim_amount   status
3     C104  Sahyadri    Surgery        125000  Pending
7     C108      Ruby  Emergency         95000  Pending

Find all claims whose claim_type is either:

Surgery \
Emergency

Use isin().

In [5]:
claims[claims['claim_type'].isin(['Surgery', 'Emergency'])]

  claim_id  hospital claim_type  claim_amount    status
0     C101    Apollo    Surgery         85000  Approved
1     C102      Ruby  Emergency         42000   Pending
3     C104  Sahyadri    Surgery        125000   Pending
4     C105      Ruby  Emergency         67000  Rejected
5     C106    Apollo    Surgery         35000   Pending
7     C108      Ruby  Emergency         95000   Pending

Find claims with claim_amount between 30,000 and 90,000 inclusive

In [6]:
claims[claims['claim_amount'].between(30000, 90000)]

  claim_id hospital claim_type  claim_amount    status
0     C101   Apollo    Surgery         85000  Approved
1     C102     Ruby  Emergency         42000   Pending
4     C105     Ruby  Emergency         67000  Rejected
5     C106   Apollo    Surgery         35000   Pending

Using loc[], return only:

claim_id, hospital, claim_amount \
for claims with claim_amount > 60000

In [13]:
claims.loc[claims['claim_amount'] > 60000, ['claim_id', 'hospital', 'claim_amount']]

  claim_id  hospital  claim_amount
0     C101    Apollo         85000
3     C104  Sahyadri        125000
4     C105      Ruby         67000
7     C108      Ruby         95000

Sort the entire dataset by claim_amount, highest first.

In [14]:
claims.sort_values('claim_amount', ascending=False)

  claim_id  hospital claim_type  claim_amount    status
3     C104  Sahyadri    Surgery        125000   Pending
7     C108      Ruby  Emergency         95000   Pending
0     C101    Apollo    Surgery         85000  Approved
4     C105      Ruby  Emergency         67000  Rejected
1     C102      Ruby  Emergency         42000   Pending
5     C106    Apollo    Surgery         35000   Pending
6     C107  Sahyadri        OPD          8000  Approved
2     C103    Apollo        OPD          5000  Approved

Return the 3 largest claims by claim_amount

In [15]:
claims.nlargest(n=3, columns='claim_amount')

  claim_id  hospital claim_type  claim_amount    status
3     C104  Sahyadri    Surgery        125000   Pending
7     C108      Ruby  Emergency         95000   Pending
0     C101    Apollo    Surgery         85000  Approved