In [1]:
import pandas as pd

### Ingest & Inspect

Load orders.csv.

In [2]:
orders = pd.read_csv("orders.csv")

Display the first 5 rows.

In [3]:
orders.head()

   order_id customer_id region product_category  amount     status
0      1001        C101   West      Electronics    4500  Delivered
1      1002        C102  South         Clothing    1200  Delivered
2      1003        C103  North      Electronics    7800    Pending
3      1004        C104   West        Furniture   15000  Delivered
4      1005        C101   West         Clothing    2200  Cancelled

Determine the dataset's shape.

In [4]:
orders.shape

(12, 6)

Inspect its columns.

In [5]:
orders.columns

Index(['order_id', 'customer_id', 'region', 'product_category', 'amount',
       'status'],
      dtype='str')

Inspect its datatypes.

In [6]:
orders.dtypes

order_id            int64
customer_id           str
region                str
product_category      str
amount              int64
status                str
dtype: object

Use info() and tell me two observations you can make about the incoming dataset.

In [7]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          12 non-null     int64
 1   customer_id       12 non-null     str
 2   region            12 non-null     str
 3   product_category  12 non-null     str
 4   amount            12 non-null     int64
 5   status            12 non-null     str
dtypes: int64(2), str(4)
memory usage: 708.0 bytes

1. customer_id is str, should be int
2. amount can be float to represent decimals

### Business Requirements

Produce a dataset containing only:
order_id, customer_id, amount, status

In [8]:
df = orders[['order_id', 'customer_id', 'amount', 'status']]

Find all orders with amount > 8000.

In [9]:
orders[orders['amount'] > 8000]

    order_id customer_id region product_category  amount     status
3       1004        C104   West        Furniture   15000  Delivered
5       1006        C105  South      Electronics    9500  Delivered
8       1009        C108   East      Electronics   12500  Delivered
9       1010        C109  South        Furniture    8100  Cancelled
11      1012        C103  North        Furniture   11000  Delivered

Find all Delivered orders.

In [10]:
orders[orders['status'] == 'Delivered']

    order_id customer_id region product_category  amount     status
0       1001        C101   West      Electronics    4500  Delivered
1       1002        C102  South         Clothing    1200  Delivered
3       1004        C104   West        Furniture   15000  Delivered
5       1006        C105  South      Electronics    9500  Delivered
7       1008        C107  North         Clothing    1800  Delivered
8       1009        C108   East      Electronics   12500  Delivered
10      1011        C110   West      Electronics    5400  Delivered
11      1012        C103  North        Furniture   11000  Delivered

Find all orders from the West region.

In [11]:
orders[orders['region'] == 'West']

    order_id customer_id region product_category  amount     status
0       1001        C101   West      Electronics    4500  Delivered
3       1004        C104   West        Furniture   15000  Delivered
4       1005        C101   West         Clothing    2200  Cancelled
10      1011        C110   West      Electronics    5400  Delivered

Find all orders belonging to the Electronics category.

In [12]:
orders[orders['product_category'] == 'Electronics']

    order_id customer_id region product_category  amount     status
0       1001        C101   West      Electronics    4500  Delivered
2       1003        C103  North      Electronics    7800    Pending
5       1006        C105  South      Electronics    9500  Delivered
8       1009        C108   East      Electronics   12500  Delivered
10      1011        C110   West      Electronics    5400  Delivered

In [14]:
orders[['amount']]

    amount
0     4500
1     1200
2     7800
3    15000
4     2200
5     9500
6     6300
7     1800
8    12500
9     8100
10    5400
11   11000