In [1]:
import pandas as pd

In [2]:
data = {
    "device_id": ["D101", "D102", "D103", "D101", "D104"],
    "event_time": [
        "2026-09-20 08:15:00",
        "2026-09-20 10:30:00",
        "invalid",
        "2026-09-20 15:45:00",
        "2026-09-21 01:10:00"
    ],
    "temperature": [42, 55, 48, 67, 39]
}

df = pd.DataFrame(data)

In [3]:
df.head()

  device_id           event_time  temperature
0      D101  2026-09-20 08:15:00           42
1      D102  2026-09-20 10:30:00           55
2      D103              invalid           48
3      D101  2026-09-20 15:45:00           67
4      D104  2026-09-21 01:10:00           39

Convert event_time to datetime. Invalid timestamps should become missing datetime values.

In [4]:
df['event_time'] = pd.to_datetime(df['event_time'], errors="coerce")

In [5]:
df

  device_id          event_time  temperature
0      D101 2026-09-20 08:15:00           42
1      D102 2026-09-20 10:30:00           55
2      D103                 NaT           48
3      D101 2026-09-20 15:45:00           67
4      D104 2026-09-21 01:10:00           39

Find all records whose timestamp failed conversion.

In [6]:
df[df['event_time'].isna()]

  device_id event_time  temperature
2      D103        NaT           48

Create an event_hour column.

In [7]:
df['event_hour'] = df['event_time'].dt.hour

In [8]:
df

  device_id          event_time  temperature  event_hour
0      D101 2026-09-20 08:15:00           42         8.0
1      D102 2026-09-20 10:30:00           55        10.0
2      D103                 NaT           48         NaN
3      D101 2026-09-20 15:45:00           67        15.0
4      D104 2026-09-21 01:10:00           39         1.0

In [9]:
df['event_date'] = df['event_time'].dt.date

In [10]:
df

  device_id          event_time  temperature  event_hour  event_date
0      D101 2026-09-20 08:15:00           42         8.0  2026-09-20
1      D102 2026-09-20 10:30:00           55        10.0  2026-09-20
2      D103                 NaT           48         NaN         NaT
3      D101 2026-09-20 15:45:00           67        15.0  2026-09-20
4      D104 2026-09-21 01:10:00           39         1.0  2026-09-21

Return events occurring from 10:00 inclusive to 16:00 exclusive on September 20.

In [11]:
df.loc[
    (df['event_hour'] >= 10) & 
    (df['event_hour'] < 16) &
    (df['event_date'].astype("str") == "2026-09-20"),
    :
]

  device_id          event_time  temperature  event_hour  event_date
1      D102 2026-09-20 10:30:00           55        10.0  2026-09-20
3      D101 2026-09-20 15:45:00           67        15.0  2026-09-20

Create window_end = event_time + 30 minutes

In [12]:
df['window_end'] = df['event_time'] + pd.Timedelta(minutes=30)

In [13]:
df

,device_id,event_time,temperature,event_hour,event_date,window_end
0,D101,2026-09-20 08:15:00,42,8.0,2026-09-20,2026-09-20 08:45:00
1,D102,2026-09-20 10:30:00,55,10.0,2026-09-20,2026-09-20 11:00:00
2,D103,NaT,48,NaN,NaT,NaT
3,D101,2026-09-20 15:45:00,67,15.0,2026-09-20,2026-09-20 16:15:00
4,D104,2026-09-21 01:10:00,39,1.0,2026-09-21,2026-09-21 01:40:00