In [1]:
import pandas as pd

In [2]:
orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005],
    "customer_id": ["C01", "C02", "C01", "C03", "C04"],
    "region": ["West", "South", "West", "North", "South"],
    "amount": [1200, 6500, 3200, 8900, 4500],
    "status": ["Delivered", "Delivered", "Cancelled", "Delivered", "Pending"]
})

First 5 rows

In [3]:
orders.head()

   order_id customer_id region  amount     status
0      1001         C01   West    1200  Delivered
1      1002         C02  South    6500  Delivered
2      1003         C01   West    3200  Cancelled
3      1004         C03  North    8900  Delivered
4      1005         C04  South    4500    Pending

Check the dataset's number of rows and columns.

In [4]:
orders.shape

(5, 5)

Select only order_id, customer_id, and amount.

In [6]:
orders[['order_id', 'customer_id', 'amount']]

   order_id customer_id  amount
0      1001         C01    1200
1      1002         C02    6500
2      1003         C01    3200
3      1004         C03    8900
4      1005         C04    4500

Return orders where amount > 4000.

In [7]:
orders[orders['amount'] > 4000]

   order_id customer_id region  amount     status
1      1002         C02  South    6500  Delivered
3      1004         C03  North    8900  Delivered
4      1005         C04  South    4500    Pending