In [1]:
import pandas as pd

In [2]:
data = {
    "shipment_id": ["S1", "S2", "S3", "S4", "S5", "S6", "S7"],
    "warehouse": ["Pune", "Pune", "Mumbai", "Mumbai", "Pune", "Delhi", "Delhi"],
    "region": ["West", "West", "West", "West", "West", "North", "North"],
    "customer_id": ["C1", "C2", "C1", "C3", "C1", "C4", "C4"],
    "revenue": [1200, 1800, 2500, 900, 1500, 3000, 2000]
}

df = pd.DataFrame(data)

In [15]:
df

  shipment_id warehouse region customer_id  revenue
0          S1      Pune   West          C1     1200
1          S2      Pune   West          C2     1800
2          S3    Mumbai   West          C1     2500
3          S4    Mumbai   West          C3      900
4          S5      Pune   West          C1     1500
5          S6     Delhi  North          C4     3000
6          S7     Delhi  North          C4     2000

Calculate total revenue by warehouse.

In [6]:
df.groupby('warehouse', as_index=False).agg(
    total_revenue=('revenue', 'sum')
)

  warehouse  total_revenue
0     Delhi           5000
1    Mumbai           3400
2      Pune           4500

Calculate average revenue by region.

In [8]:
df.groupby('region', as_index=False).agg(
    avg_revenue=('revenue', 'mean')
)

  region  avg_revenue
0  North       2500.0
1   West       1580.0

In [9]:
df.groupby('warehouse', as_index=False).agg(
    unique_customers=('customer_id', 'nunique')
)

  warehouse  unique_customers
0     Delhi                 1
1    Mumbai                 2
2      Pune                 2

Produce one warehouse-level table containing:

- total_revenue
- avg_revenue
- max_revenue
- unique_customers

In [10]:
df.groupby('warehouse', as_index=False).agg(
    total_revenue=('revenue', 'sum'),
    avg_revenue=('revenue', 'mean'),
    max_revenue=('revenue', 'max'),
    unique_customers=('customer_id', 'nunique')
)

  warehouse  total_revenue  avg_revenue  max_revenue  unique_customers
0     Delhi           5000       2500.0         3000                 1
1    Mumbai           3400       1700.0         2500                 2
2      Pune           4500       1500.0         1800                 2

Produce revenue grouped by region + warehouse.

In [11]:
df.groupby(['region', 'warehouse'], as_index=False).agg(
    total_revenue=('revenue', 'sum')
)

  region warehouse  total_revenue
0  North     Delhi           5000
1   West    Mumbai           3400
2   West      Pune           4500