In [1]:
import pandas as pd

orders_json = [
    {
        "order_id": "ORD1001",
        "order_date": "2026-09-25",
        "status": "DELIVERED",
        "customer": {
            "customer_id": "C101",
            "name": "Aarav",
            "city": "Pune"
        },
        "shipping": {
            "method": "EXPRESS",
            "warehouse_id": "WH01"
        },
        "items": [
            {
                "product_id": "P101",
                "product_name": "Keyboard",
                "quantity": 2,
                "unit_price": 2500
            },
            {
                "product_id": "P102",
                "product_name": "Mouse",
                "quantity": 1,
                "unit_price": 1200
            }
        ]
    },
    {
        "order_id": "ORD1002",
        "order_date": "2026-09-26",
        "status": "DELIVERED",
        "customer": {
            "customer_id": "C102",
            "name": "Meera",
            "city": "Mumbai"
        },
        "shipping": {
            "method": "STANDARD",
            "warehouse_id": "WH02"
        },
        "items": [
            {
                "product_id": "P103",
                "product_name": "Monitor",
                "quantity": 1,
                "unit_price": 18000
            }
        ]
    },
    {
        "order_id": "ORD1003",
        "order_date": "2026-09-27",
        "status": "CANCELLED",
        "customer": {
            "customer_id": "C103",
            "name": "Kabir",
            "city": "Pune"
        },
        "shipping": {
            "method": "STANDARD",
            "warehouse_id": "WH01"
        },
        "items": [
            {
                "product_id": "P104",
                "product_name": "Webcam",
                "quantity": 1,
                "unit_price": 3500
            }
        ]
    },
    {
        "order_id": "ORD1004",
        "order_date": "2026-09-28",
        "status": "DELIVERED",
        "customer": {
            "customer_id": "C104",
            "name": "Ishita",
            "city": "Bengaluru"
        },
        "shipping": {
            "method": "EXPRESS",
            "warehouse_id": "WH03"
        },
        "items": [
            {
                "product_id": "P101",
                "product_name": "Keyboard",
                "quantity": 1,
                "unit_price": 2500
            },
            {
                "product_id": "P104",
                "product_name": "Webcam",
                "quantity": 2,
                "unit_price": 3500
            },
            {
                "product_id": "P105",
                "product_name": "USB Hub",
                "quantity": 3,
                "unit_price": 800
            }
        ]
    },
    {
        "order_id": "ORD1005",
        "order_date": "2026-09-29",
        "status": "DELIVERED",
        "customer": {
            "customer_id": "C105",
            "name": "Rohan",
            "city": "Delhi"
        },
        "shipping": {
            "method": "STANDARD",
            "warehouse_id": "WH02"
        },
        "items": []
    }
]

In [2]:
df = pd.json_normalize(orders_json, sep='_')

In [3]:
df

,order_id,order_date,status,items,customer_customer_id,customer_name,customer_city,shipping_method,shipping_warehouse_id
0,ORD1001,2026-09-25,DELIVERED,"[{'product_id': 'P101', 'product_name': 'Keybo...",C101,Aarav,Pune,EXPRESS,WH01
1,ORD1002,2026-09-26,DELIVERED,"[{'product_id': 'P103', 'product_name': 'Monit...",C102,Meera,Mumbai,STANDARD,WH02
2,ORD1003,2026-09-27,CANCELLED,"[{'product_id': 'P104', 'product_name': 'Webca...",C103,Kabir,Pune,STANDARD,WH01
3,ORD1004,2026-09-28,DELIVERED,"[{'product_id': 'P101', 'product_name': 'Keybo...",C104,Ishita,Bengaluru,EXPRESS,WH03
4,ORD1005,2026-09-29,DELIVERED,[],C105,Rohan,Delhi,STANDARD,WH02

In [4]:
exploded_df = df.explode('items')

In [5]:
exploded_df

,order_id,order_date,status,items,customer_customer_id,customer_name,customer_city,shipping_method,shipping_warehouse_id
0,ORD1001,2026-09-25,DELIVERED,"{'product_id': 'P101', 'product_name': 'Keyboa...",C101,Aarav,Pune,EXPRESS,WH01
0,ORD1001,2026-09-25,DELIVERED,"{'product_id': 'P102', 'product_name': 'Mouse'...",C101,Aarav,Pune,EXPRESS,WH01
1,ORD1002,2026-09-26,DELIVERED,"{'product_id': 'P103', 'product_name': 'Monito...",C102,Meera,Mumbai,STANDARD,WH02
2,ORD1003,2026-09-27,CANCELLED,"{'product_id': 'P104', 'product_name': 'Webcam...",C103,Kabir,Pune,STANDARD,WH01
3,ORD1004,2026-09-28,DELIVERED,"{'product_id': 'P101', 'product_name': 'Keyboa...",C104,Ishita,Bengaluru,EXPRESS,WH03
3,ORD1004,2026-09-28,DELIVERED,"{'product_id': 'P104', 'product_name': 'Webcam...",C104,Ishita,Bengaluru,EXPRESS,WH03
3,ORD1004,2026-09-28,DELIVERED,"{'product_id': 'P105', 'product_name': 'USB Hu...",C104,Ishita,Bengaluru,EXPRESS,WH03
4,ORD1005,2026-09-29,DELIVERED,NaN,C105,Rohan,Delhi,STANDARD,WH02

In [6]:
products = pd.json_normalize(orders_json, record_path='items', meta=['order_id'])

In [7]:
products

  product_id product_name  quantity  unit_price order_id
0       P101     Keyboard         2        2500  ORD1001
1       P102        Mouse         1        1200  ORD1001
2       P103      Monitor         1       18000  ORD1002
3       P104       Webcam         1        3500  ORD1003
4       P101     Keyboard         1        2500  ORD1004
5       P104       Webcam         2        3500  ORD1004
6       P105      USB Hub         3         800  ORD1004

In [8]:
products['item_revenue'] = products['quantity'] * products['unit_price']

In [9]:
products

  product_id product_name  quantity  unit_price order_id  item_revenue
0       P101     Keyboard         2        2500  ORD1001          5000
1       P102        Mouse         1        1200  ORD1001          1200
2       P103      Monitor         1       18000  ORD1002         18000
3       P104       Webcam         1        3500  ORD1003          3500
4       P101     Keyboard         1        2500  ORD1004          2500
5       P104       Webcam         2        3500  ORD1004          7000
6       P105      USB Hub         3         800  ORD1004          2400

In [10]:
exploded_df = exploded_df.loc[
    :,
    [
        'order_id',
        'order_date',
        'status',
        'customer_customer_id',
        'customer_name',
        'customer_city',
        'shipping_method',
        'shipping_warehouse_id'
    ]
]

In [11]:
products

  product_id product_name  quantity  unit_price order_id  item_revenue
0       P101     Keyboard         2        2500  ORD1001          5000
1       P102        Mouse         1        1200  ORD1001          1200
2       P103      Monitor         1       18000  ORD1002         18000
3       P104       Webcam         1        3500  ORD1003          3500
4       P101     Keyboard         1        2500  ORD1004          2500
5       P104       Webcam         2        3500  ORD1004          7000
6       P105      USB Hub         3         800  ORD1004          2400

In [12]:
exploded_df = exploded_df.drop_duplicates()

In [13]:
exploded_df

,order_id,order_date,status,customer_customer_id,customer_name,customer_city,shipping_method,shipping_warehouse_id
0,ORD1001,2026-09-25,DELIVERED,C101,Aarav,Pune,EXPRESS,WH01
1,ORD1002,2026-09-26,DELIVERED,C102,Meera,Mumbai,STANDARD,WH02
2,ORD1003,2026-09-27,CANCELLED,C103,Kabir,Pune,STANDARD,WH01
3,ORD1004,2026-09-28,DELIVERED,C104,Ishita,Bengaluru,EXPRESS,WH03
4,ORD1005,2026-09-29,DELIVERED,C105,Rohan,Delhi,STANDARD,WH02

In [15]:
final_df = exploded_df.merge(
    products,
    on='order_id',
    how='inner'
)

In [16]:
final_df

,order_id,order_date,status,customer_customer_id,customer_name,customer_city,shipping_method,shipping_warehouse_id,product_id,product_name,quantity,unit_price,item_revenue
0,ORD1001,2026-09-25,DELIVERED,C101,Aarav,Pune,EXPRESS,WH01,P101,Keyboard,2,2500,5000
1,ORD1001,2026-09-25,DELIVERED,C101,Aarav,Pune,EXPRESS,WH01,P102,Mouse,1,1200,1200
2,ORD1002,2026-09-26,DELIVERED,C102,Meera,Mumbai,STANDARD,WH02,P103,Monitor,1,18000,18000
3,ORD1003,2026-09-27,CANCELLED,C103,Kabir,Pune,STANDARD,WH01,P104,Webcam,1,3500,3500
4,ORD1004,2026-09-28,DELIVERED,C104,Ishita,Bengaluru,EXPRESS,WH03,P101,Keyboard,1,2500,2500
5,ORD1004,2026-09-28,DELIVERED,C104,Ishita,Bengaluru,EXPRESS,WH03,P104,Webcam,2,3500,7000
6,ORD1004,2026-09-28,DELIVERED,C104,Ishita,Bengaluru,EXPRESS,WH03,P105,USB Hub,3,800,2400

1. How many unique orders were received?

In [17]:
final_df['order_id'].nunique()

4

2. How many item records exist after flattening? \
-> 6

3. What is the total revenue from DELIVERED orders only?

In [25]:
final_df.groupby('status').agg(
    total_revenue=('item_revenue', 'sum')
).loc['DELIVERED']

total_revenue    36100
Name: DELIVERED, dtype: int64

4. Calculate delivered revenue by customer_city.

In [29]:
final_df[final_df['status'] == 'DELIVERED'].groupby('customer_city').agg(
    total_revenue=('item_revenue', 'sum')
)

               total_revenue
customer_city
Bengaluru              11900
Mumbai                 18000
Pune                    6200

5. Which product_id generated the highest delivered revenue?

In [37]:
final_df[final_df['status'] == 'DELIVERED'].sort_values('item_revenue', ascending=False).iloc[0]

order_id                    ORD1002
order_date               2026-09-26
status                    DELIVERED
customer_customer_id           C102
customer_name                 Meera
customer_city                Mumbai
shipping_method            STANDARD
shipping_warehouse_id          WH02
product_id                     P103
product_name                Monitor
quantity                          1
unit_price                    18000
item_revenue                  18000
Name: 2, dtype: object