In [1]:
import pandas as pd

In [2]:
events = pd.DataFrame({
    "account_id": [101, 101, 102, 102, 102, 103],
    "status": [
        "ACTIVE", "BLOCKED",
        "ACTIVE", "SUSPENDED", "ACTIVE",
        "ACTIVE"
    ],
    "updated_at": pd.to_datetime([
        "2026-09-20 09:00",
        "2026-09-20 11:00",
        "2026-09-20 08:00",
        "2026-09-20 12:00",
        "2026-09-20 12:00",
        "2026-09-20 10:00"
    ]),
    "event_sequence": [1, 2, 1, 2, 3, 1]
})

In [3]:
events

   account_id     status          updated_at  event_sequence
0         101     ACTIVE 2026-09-20 09:00:00               1
1         101    BLOCKED 2026-09-20 11:00:00               2
2         102     ACTIVE 2026-09-20 08:00:00               1
3         102  SUSPENDED 2026-09-20 12:00:00               2
4         102     ACTIVE 2026-09-20 12:00:00               3
5         103     ACTIVE 2026-09-20 10:00:00               1

In [4]:
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   account_id      6 non-null      int64
 1   status          6 non-null      str
 2   updated_at      6 non-null      datetime64[us]
 3   event_sequence  6 non-null      int64
dtypes: datetime64[us](1), int64(2), str(1)
memory usage: 324.0 bytes

Sort the events by account_id and then updated_at.

In [5]:
sorted_df = events.sort_values(
    ['account_id', 'updated_at']
)

In [6]:
sorted_df

   account_id     status          updated_at  event_sequence
0         101     ACTIVE 2026-09-20 09:00:00               1
1         101    BLOCKED 2026-09-20 11:00:00               2
2         102     ACTIVE 2026-09-20 08:00:00               1
3         102  SUSPENDED 2026-09-20 12:00:00               2
4         102     ACTIVE 2026-09-20 12:00:00               3
5         103     ACTIVE 2026-09-20 10:00:00               1

Using sort + drop_duplicates(), return one latest row per account. Account 102 has a timestamp tie, so use event_sequence as the tie-breaker.

In [7]:
sorted_events = events.sort_values(
    ['account_id', 'updated_at', 'event_sequence']
)

In [8]:
sorted_events.drop_duplicates(
    subset=['account_id'],
    keep='last'
)

   account_id   status          updated_at  event_sequence
1         101  BLOCKED 2026-09-20 11:00:00               2
4         102   ACTIVE 2026-09-20 12:00:00               3
5         103   ACTIVE 2026-09-20 10:00:00               1

Using groupby().idxmax(), return the row having the maximum updated_at for each account.

In [9]:
idx = sorted_events.groupby('account_id')['updated_at'].idxmax()
events.loc[idx]

   account_id     status          updated_at  event_sequence
1         101    BLOCKED 2026-09-20 11:00:00               2
3         102  SUSPENDED 2026-09-20 12:00:00               2
5         103     ACTIVE 2026-09-20 10:00:00               1