In [1]:
import pandas as pd

In [2]:
account_cdc = pd.DataFrame({
    "account_id": [
        1001, 1001,
        1002, 1002, 1002,
        1003, 1003,
        1004,
        1005, 1005, 1005
    ],

    "status": [
        "ACTIVE", "BLOCKED",
        "ACTIVE", "SUSPENDED", "SUSPENDED",
        "ACTIVE", "CLOSED",
        "ACTIVE",
        "ACTIVE", "SUSPENDED", "ACTIVE"
    ],

    "credit_limit": [
        50000, 50000,
        30000, 30000, 30000,
        75000, 75000,
        20000,
        40000, 40000, 60000
    ],

    "updated_at": pd.to_datetime([
        "2026-09-27 08:00",
        "2026-09-27 11:30",

        "2026-09-27 09:00",
        "2026-09-27 12:00",
        "2026-09-27 12:00",

        "2026-09-27 07:30",
        "2026-09-27 15:00",

        "2026-09-27 10:00",

        "2026-09-27 08:30",
        "2026-09-27 14:00",
        "2026-09-27 14:00"
    ]),

    "event_sequence": [
        1, 2,
        1, 2, 2,
        1, 2,
        1,
        1, 2, 3
    ]
})

In [3]:
account_cdc

    account_id     status  credit_limit          updated_at  event_sequence
0         1001     ACTIVE         50000 2026-09-27 08:00:00               1
1         1001    BLOCKED         50000 2026-09-27 11:30:00               2
2         1002     ACTIVE         30000 2026-09-27 09:00:00               1
3         1002  SUSPENDED         30000 2026-09-27 12:00:00               2
4         1002  SUSPENDED         30000 2026-09-27 12:00:00               2
5         1003     ACTIVE         75000 2026-09-27 07:30:00               1
6         1003     CLOSED         75000 2026-09-27 15:00:00               2
7         1004     ACTIVE         20000 2026-09-27 10:00:00               1
8         1005     ACTIVE         40000 2026-09-27 08:30:00               1
9         1005  SUSPENDED         40000 2026-09-27 14:00:00               2
10        1005     ACTIVE         60000 2026-09-27 14:00:00               3

In [4]:
sorted_df = account_cdc.sort_values(
    ['account_id', 'updated_at', 'event_sequence']
)

In [5]:
sorted_df

    account_id     status  credit_limit          updated_at  event_sequence
0         1001     ACTIVE         50000 2026-09-27 08:00:00               1
1         1001    BLOCKED         50000 2026-09-27 11:30:00               2
2         1002     ACTIVE         30000 2026-09-27 09:00:00               1
3         1002  SUSPENDED         30000 2026-09-27 12:00:00               2
4         1002  SUSPENDED         30000 2026-09-27 12:00:00               2
5         1003     ACTIVE         75000 2026-09-27 07:30:00               1
6         1003     CLOSED         75000 2026-09-27 15:00:00               2
7         1004     ACTIVE         20000 2026-09-27 10:00:00               1
8         1005     ACTIVE         40000 2026-09-27 08:30:00               1
9         1005  SUSPENDED         40000 2026-09-27 14:00:00               2
10        1005     ACTIVE         60000 2026-09-27 14:00:00               3

In [6]:
latest_accounts = sorted_df.drop_duplicates(
    subset=['account_id'],
    keep='last'
)

In [7]:
latest_accounts = latest_accounts.sort_values(['account_id'])

In [8]:
latest_accounts

    account_id     status  credit_limit          updated_at  event_sequence
1         1001    BLOCKED         50000 2026-09-27 11:30:00               2
4         1002  SUSPENDED         30000 2026-09-27 12:00:00               2
6         1003     CLOSED         75000 2026-09-27 15:00:00               2
7         1004     ACTIVE         20000 2026-09-27 10:00:00               1
10        1005     ACTIVE         60000 2026-09-27 14:00:00               3

Validation

In [9]:
latest_accounts['account_id'].nunique() == account_cdc['account_id'].nunique()

True

In [10]:
latest_accounts['account_id'].duplicated()

1     False
4     False
6     False
7     False
10    False
Name: account_id, dtype: bool