In [1]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [
        "O101", "O102", "O103", "O104",
        "O105", "O106", "O107", "O108",
        "O109", "O110", "O111", "O112"
    ],
    
    "seller_id": [
        "S01", "S02", "S01", "S03",
        "S03", "S04", "S05", "S04",
        "S05", "S06", "S02", "S06"
    ],
    
    "category": [
        "Electronics", "Electronics", "Electronics", "Electronics",
        "Electronics", "Furniture", "Furniture", "Furniture",
        "Furniture", "Furniture", "Electronics", "Furniture"
    ],
    
    "order_date": [
        "2026-08-02", "2026-08-04", "2026-08-08", "2026-08-10",
        "2026-08-15", "2026-08-03", "2026-08-06", "2026-08-12",
        "2026-08-18", "2026-08-20", "2026-07-29", "2026-08-22"
    ],
    
    "amount": [
        1200, 1800, 800, 2000,
        2000, 1500, 1000, 500,
        1000, 700, 5000, 300
    ],
    
    "status": [
        "Delivered", "Delivered", "Delivered", "Cancelled",
        "Delivered", "Delivered", "Delivered", "Delivered",
        "Delivered", "Delivered", "Delivered", "Cancelled"
    ]
})

In [2]:
orders.head()

  order_id seller_id     category  order_date  amount     status
0     O101       S01  Electronics  2026-08-02    1200  Delivered
1     O102       S02  Electronics  2026-08-04    1800  Delivered
2     O103       S01  Electronics  2026-08-08     800  Delivered
3     O104       S03  Electronics  2026-08-10    2000  Cancelled
4     O105       S03  Electronics  2026-08-15    2000  Delivered

In [3]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    12 non-null     str
 1   seller_id   12 non-null     str
 2   category    12 non-null     str
 3   order_date  12 non-null     str
 4   amount      12 non-null     int64
 5   status      12 non-null     str
dtypes: int64(1), str(5)
memory usage: 708.0 bytes

In [4]:
orders[orders.duplicated()]

Empty DataFrame
Columns: [order_id, seller_id, category, order_date, amount, status]
Index: []

Converting order date to datatime

In [5]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [6]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    12 non-null     str
 1   seller_id   12 non-null     str
 2   category    12 non-null     str
 3   order_date  12 non-null     datetime64[us]
 4   amount      12 non-null     int64
 5   status      12 non-null     str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 708.0 bytes

In [7]:
filtered_orders = orders.loc[
    (orders['order_date'] >= '2026-08-01') & 
    (orders['order_date'] < '2026-09-01') &
    (orders['status'] == 'Delivered'), 
    :
]

In [8]:
filtered_orders

  order_id seller_id     category order_date  amount     status
0     O101       S01  Electronics 2026-08-02    1200  Delivered
1     O102       S02  Electronics 2026-08-04    1800  Delivered
2     O103       S01  Electronics 2026-08-08     800  Delivered
4     O105       S03  Electronics 2026-08-15    2000  Delivered
5     O106       S04    Furniture 2026-08-03    1500  Delivered
6     O107       S05    Furniture 2026-08-06    1000  Delivered
7     O108       S04    Furniture 2026-08-12     500  Delivered
8     O109       S05    Furniture 2026-08-18    1000  Delivered
9     O110       S06    Furniture 2026-08-20     700  Delivered

In [9]:
grouped = filtered_orders.groupby(['seller_id', 'category'], as_index=False).agg(
    total_revenue=('amount', 'sum'),
    order_count=('order_id', 'count')
)

In [10]:
grouped

  seller_id     category  total_revenue  order_count
0       S01  Electronics           2000            2
1       S02  Electronics           1800            1
2       S03  Electronics           2000            1
3       S04    Furniture           2000            2
4       S05    Furniture           2000            2
5       S06    Furniture            700            1

In [11]:
grouped['category_avg_revenue'] = grouped.groupby('category')['total_revenue'].transform('mean')

In [12]:
grouped

  seller_id     category  total_revenue  order_count  category_avg_revenue
0       S01  Electronics           2000            2           1933.333333
1       S02  Electronics           1800            1           1933.333333
2       S03  Electronics           2000            1           1933.333333
3       S04    Furniture           2000            2           1566.666667
4       S05    Furniture           2000            2           1566.666667
5       S06    Furniture            700            1           1566.666667

In [13]:
grouped['revenue_vs_category_avg'] = grouped['total_revenue'] - grouped['category_avg_revenue']

In [14]:
grouped

,seller_id,category,total_revenue,order_count,category_avg_revenue,revenue_vs_category_avg
0,S01,Electronics,2000,2,1933.333333,66.666667
1,S02,Electronics,1800,1,1933.333333,-133.333333
2,S03,Electronics,2000,1,1933.333333,66.666667
3,S04,Furniture,2000,2,1566.666667,433.333333
4,S05,Furniture,2000,2,1566.666667,433.333333
5,S06,Furniture,700,1,1566.666667,-866.666667

In [15]:
grouped['category_total_revenue'] = grouped.groupby('category')['total_revenue'].transform('sum')

In [16]:
grouped

,seller_id,category,total_revenue,order_count,category_avg_revenue,revenue_vs_category_avg,category_total_revenue
0,S01,Electronics,2000,2,1933.333333,66.666667,5800
1,S02,Electronics,1800,1,1933.333333,-133.333333,5800
2,S03,Electronics,2000,1,1933.333333,66.666667,5800
3,S04,Furniture,2000,2,1566.666667,433.333333,4700
4,S05,Furniture,2000,2,1566.666667,433.333333,4700
5,S06,Furniture,700,1,1566.666667,-866.666667,4700

In [17]:
grouped['category_revenue_share'] = grouped['total_revenue'] / grouped['category_total_revenue']

In [18]:
grouped

,seller_id,category,total_revenue,order_count,category_avg_revenue,revenue_vs_category_avg,category_total_revenue,category_revenue_share
0,S01,Electronics,2000,2,1933.333333,66.666667,5800,0.344828
1,S02,Electronics,1800,1,1933.333333,-133.333333,5800,0.310345
2,S03,Electronics,2000,1,1933.333333,66.666667,5800,0.344828
3,S04,Furniture,2000,2,1566.666667,433.333333,4700,0.425532
4,S05,Furniture,2000,2,1566.666667,433.333333,4700,0.425532
5,S06,Furniture,700,1,1566.666667,-866.666667,4700,0.148936

In [19]:
grouped['revenue_rank'] = grouped.groupby('category')['total_revenue'].rank(method='dense', ascending=False)

In [20]:
grouped

,seller_id,category,total_revenue,order_count,category_avg_revenue,revenue_vs_category_avg,category_total_revenue,category_revenue_share,revenue_rank
0,S01,Electronics,2000,2,1933.333333,66.666667,5800,0.344828,1.0
1,S02,Electronics,1800,1,1933.333333,-133.333333,5800,0.310345,2.0
2,S03,Electronics,2000,1,1933.333333,66.666667,5800,0.344828,1.0
3,S04,Furniture,2000,2,1566.666667,433.333333,4700,0.425532,1.0
4,S05,Furniture,2000,2,1566.666667,433.333333,4700,0.425532,1.0
5,S06,Furniture,700,1,1566.666667,-866.666667,4700,0.148936,2.0

In [21]:
grouped.sort_values(['category', 'revenue_rank', 'seller_id'])

,seller_id,category,total_revenue,order_count,category_avg_revenue,revenue_vs_category_avg,category_total_revenue,category_revenue_share,revenue_rank
0,S01,Electronics,2000,2,1933.333333,66.666667,5800,0.344828,1.0
2,S03,Electronics,2000,1,1933.333333,66.666667,5800,0.344828,1.0
1,S02,Electronics,1800,1,1933.333333,-133.333333,5800,0.310345,2.0
3,S04,Furniture,2000,2,1566.666667,433.333333,4700,0.425532,1.0
4,S05,Furniture,2000,2,1566.666667,433.333333,4700,0.425532,1.0
5,S06,Furniture,700,1,1566.666667,-866.666667,4700,0.148936,2.0