In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "region": ["West", "West", "West", "East", "East", "East"],
    "salesperson": ["A", "B", "C", "D", "E", "F"],
    "revenue": [500, 800, 500, 900, 600, 600],
    "orders": [10, 15, 8, 20, 12, 14]
})

In [3]:
df.head()

  region salesperson  revenue  orders
0   West           A      500      10
1   West           B      800      15
2   West           C      500       8
3   East           D      900      20
4   East           E      600      12

Create:
- revenue_rank

- Rank salespeople by revenue within their region, highest revenue first.
- Tied revenue should receive the same rank and the next rank should not have a gap.

In [9]:
df['revenue_rank'] = df.groupby('region')['revenue'].rank(method='dense', ascending=False)

In [15]:
df.sort_values(['region', 'revenue_rank'])

  region salesperson  revenue  orders  revenue_rank
3   East           D      900      20           1.0
4   East           E      600      12           2.0
5   East           F      600      14           2.0
1   West           B      800      15           1.0
0   West           A      500      10           2.0
2   West           C      500       8           2.0

Create:
- region_avg_revenue

- containing the average revenue of that salesperson's region while keeping all six original rows.

In [17]:
df['region_avg_revenue'] = df.groupby('region')['revenue'].transform('mean')

In [18]:
df

  region salesperson  revenue  orders  revenue_rank  region_avg_revenue
0   West           A      500      10           2.0               600.0
1   West           B      800      15           1.0               600.0
2   West           C      500       8           2.0               600.0
3   East           D      900      20           1.0               700.0
4   East           E      600      12           2.0               700.0
5   East           F      600      14           2.0               700.0

Using the column created in Q2, create:
- above_region_avg

- which is True when the salesperson's revenue is greater than their region average.

In [20]:
df['above_region_revenue'] = df['revenue'] > df['region_avg_revenue']

In [22]:
df

,region,salesperson,revenue,orders,revenue_rank,region_avg_revenue,above_region_revenue
0,West,A,500,10,2.0,600.0,False
1,West,B,800,15,1.0,600.0,True
2,West,C,500,8,2.0,600.0,False
3,East,D,900,20,1.0,700.0,True
4,East,E,600,12,2.0,700.0,False
5,East,F,600,14,2.0,700.0,False

Create:
- region_total_revenue
- revenue_share

- where revenue_share represents each salesperson's contribution to their region's total revenue.
- For example, 0.25 means 25% of regional revenue.

In [24]:
df['region_total_revenue'] = df.groupby('region')['revenue'].transform('sum')

In [25]:
df

,region,salesperson,revenue,orders,revenue_rank,region_avg_revenue,above_region_revenue,region_total_revenue
0,West,A,500,10,2.0,600.0,False,1800
1,West,B,800,15,1.0,600.0,True,1800
2,West,C,500,8,2.0,600.0,False,1800
3,East,D,900,20,1.0,700.0,True,2100
4,East,E,600,12,2.0,700.0,False,2100
5,East,F,600,14,2.0,700.0,False,2100

In [30]:
df['revenue_share'] = df['revenue'] / df['region_total_revenue'] * 100

In [31]:
df

,region,salesperson,revenue,orders,revenue_rank,region_avg_revenue,above_region_revenue,region_total_revenue,revenue_share
0,West,A,500,10,2.0,600.0,False,1800,27.777778
1,West,B,800,15,1.0,600.0,True,1800,44.444444
2,West,C,500,8,2.0,600.0,False,1800,27.777778
3,East,D,900,20,1.0,700.0,True,2100,42.857143
4,East,E,600,12,2.0,700.0,False,2100,28.571429
5,East,F,600,14,2.0,700.0,False,2100,28.571429