In [2]:
import pandas as pd
import numpy as np

In [3]:
transactions = pd.DataFrame({
    "transaction_id": [101, 102, 103, 104, 105, 106],
    "customer_id": ["C1", "C2", "C3", "C1", "C4", "C5"],
    "amount": [1200, 75000, 42000, 110000, 800, 65000],
    "payment_method": ["UPI", "CARD", "CARD", "UPI", "CASH", "CARD"],
    "country": ["IN", "IN", "US", "SG", "IN", "US"]
})

In [4]:
transactions.head()

   transaction_id customer_id  amount payment_method country
0             101          C1    1200            UPI      IN
1             102          C2   75000           CARD      IN
2             103          C3   42000           CARD      US
3             104          C1  110000            UPI      SG
4             105          C4     800           CASH      IN

Create high_value_flag:

- "Y" when amount >= 50000
- "N" otherwise
- Use np.where().

In [6]:
transactions['high_value'] = np.where(
    transactions['amount'] >= 50000,
    "Y",
    "N"
)

In [7]:
transactions

   transaction_id customer_id  amount payment_method country high_value
0             101          C1    1200            UPI      IN          N
1             102          C2   75000           CARD      IN          Y
2             103          C3   42000           CARD      US          N
3             104          C1  110000            UPI      SG          Y
4             105          C4     800           CASH      IN          N
5             106          C5   65000           CARD      US          Y

Create international_flag:

- "Y" when country != "IN"
- "N" otherwise.

In [8]:
transactions['international_flag'] = np.where(
    transactions['country'] != "IN",
    "Y",
    "N"
)

In [9]:
transactions

,transaction_id,customer_id,amount,payment_method,country,high_value,international_flag
0,101,C1,1200,UPI,IN,N,N
1,102,C2,75000,CARD,IN,Y,N
2,103,C3,42000,CARD,US,N,Y
3,104,C1,110000,UPI,SG,Y,Y
4,105,C4,800,CASH,IN,N,N
5,106,C5,65000,CARD,US,Y,Y

Given:
payment_risk = {
    "UPI": "LOW",
    "CARD": "MEDIUM",
    "CASH": "HIGH"
}

Create payment_risk using map().

In [10]:
payment_risk = {
    "UPI": "LOW",
    "CARD": "MEDIUM",
    "CASH": "HIGH"
}

In [12]:
transactions['payment_risk'] = transactions['payment_method'].map(payment_risk)

In [13]:
transactions

,transaction_id,customer_id,amount,payment_method,country,high_value,international_flag,payment_risk
0,101,C1,1200,UPI,IN,N,N,LOW
1,102,C2,75000,CARD,IN,Y,N,MEDIUM
2,103,C3,42000,CARD,US,N,Y,MEDIUM
3,104,C1,110000,UPI,SG,Y,Y,LOW
4,105,C4,800,CASH,IN,N,N,HIGH
5,106,C5,65000,CARD,US,Y,Y,MEDIUM

Create amount_with_fee using a vectorized operation:
- amount_with_fee = amount * 1.02

In [15]:
transactions['amount_with_fee'] = transactions['amount'] * 1.02

In [16]:
transactions

,transaction_id,customer_id,amount,payment_method,country,high_value,international_flag,payment_risk,amount_with_fee
0,101,C1,1200,UPI,IN,N,N,LOW,1224.0
1,102,C2,75000,CARD,IN,Y,N,MEDIUM,76500.0
2,103,C3,42000,CARD,US,N,Y,MEDIUM,42840.0
3,104,C1,110000,UPI,SG,Y,Y,LOW,112200.0
4,105,C4,800,CASH,IN,N,N,HIGH,816.0
5,106,C5,65000,CARD,US,Y,Y,MEDIUM,66300.0

Create review_flag:
- REVIEW if:
  - amount >= 50000
  - AND
  - country != "IN"

otherwise:
- OK

In [18]:
transactions['review_flag'] = np.where(
    (transactions['amount'] >= 50000) & 
    (transactions['country'] != 'IN'),
    "REVIEW",
    "OK"
)

In [19]:
transactions

,transaction_id,customer_id,amount,payment_method,country,high_value,international_flag,payment_risk,amount_with_fee,review_flag
0,101,C1,1200,UPI,IN,N,N,LOW,1224.0,OK
1,102,C2,75000,CARD,IN,Y,N,MEDIUM,76500.0,OK
2,103,C3,42000,CARD,US,N,Y,MEDIUM,42840.0,OK
3,104,C1,110000,UPI,SG,Y,Y,LOW,112200.0,REVIEW
4,105,C4,800,CASH,IN,N,N,HIGH,816.0,OK
5,106,C5,65000,CARD,US,Y,Y,MEDIUM,66300.0,REVIEW