In [1]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    "order_id": [
        "O101", "O102", "O103", "O104", "O105",
        "O106", "O107", "O108", "O108", "O109",
        "O110", "O111"
    ],

    "customer_id": [
        "C01", "C02", "C03", "C01", "C04",
        "C05", "C06", "C07", "C07", "C08",
        "C09", None
    ],

    "order_date": [
        "2026-10-01 09:15:00",
        "2026-10-01 10:30:00",
        "2026-10-01 11:00:00",
        "2026-10-02 08:45:00",
        "2026-10-02 09:30:00",
        "2026-10-02 11:20:00",
        "2026-10-02 14:00:00",
        "2026-10-03 09:00:00",
        "2026-10-03 09:00:00",
        "2026-10-03 12:00:00",
        "2026-10-03 14:30:00",
        "2026-10-03 16:00:00"
    ],

    "amount": [
        1200, 2500, 800, 4000, -500,
        3200, 1500, 2700, 2700, 5000,
        1800, 2200
    ],

    "order_status": [
        "completed", "COMPLETED", " Completed ",
        "completed", "COMPLETED",
        "cancelled", "COMPLETED", "completed",
        "completed", "UNKNOWN", "COMPLETED", "COMPLETED"
    ]
})

In [2]:
customers = pd.DataFrame({
    "customer_id": [
        "C01", "C02", "C03", "C04", "C05",
        "C06", "C07", "C07", "C08", "C09"
    ],

    "customer_name": [
        "Aarav", "Diya", "Kabir", "Meera", "Ishaan",
        "Riya", "Arjun", "Arjun", "Sara", "Vivaan"
    ],

    "region": [
        "West", "south", "WEST", "North", None,
        " South ", "East", "WEST", "East", "North"
    ],

    "updated_at": [
        "2026-09-20 10:00:00",
        "2026-09-21 11:00:00",
        "2026-09-22 09:00:00",
        "2026-09-22 15:00:00",
        "2026-09-23 10:00:00",
        "2026-09-24 13:00:00",
        "2026-09-20 09:00:00",
        "2026-09-29 18:00:00",
        "2026-09-25 08:00:00",
        "2026-09-26 17:00:00"
    ]
})

In [3]:
payments = pd.DataFrame({
    "payment_id": [
        "P001", "P002", "P003", "P004", "P005",
        "P006", "P007", "P008", "P008", "P009",
        "P010", "P011"
    ],

    "order_id": [
        "O101", "O102", "O103", "O104", "O105",
        "O106", "O107", "O108", "O108", "O999",
        "O110", "O109"
    ],

    "payment_status": [
        "SUCCESS", "success", "FAILED", "SUCCESS", "SUCCESS",
        "SUCCESS", " Success ", "SUCCESS", "SUCCESS", "SUCCESS",
        "FAILED", "SUCCESS"
    ],

    "payment_amount": [
        1200, 2500, 800, 4000, 500,
        3200, 1500, 2700, 2700, 999,
        1800, 5000
    ]
})

## Inspect

In [4]:
orders.head()

  order_id customer_id           order_date  amount order_status
0     O101         C01  2026-10-01 09:15:00    1200    completed
1     O102         C02  2026-10-01 10:30:00    2500    COMPLETED
2     O103         C03  2026-10-01 11:00:00     800   Completed
3     O104         C01  2026-10-02 08:45:00    4000    completed
4     O105         C04  2026-10-02 09:30:00    -500    COMPLETED

In [5]:
orders[orders['amount'] < 0]

  order_id customer_id           order_date  amount order_status
4     O105         C04  2026-10-02 09:30:00    -500    COMPLETED

In [6]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      12 non-null     str
 1   customer_id   11 non-null     str
 2   order_date    12 non-null     str
 3   amount        12 non-null     int64
 4   order_status  12 non-null     str
dtypes: int64(1), str(4)
memory usage: 612.0 bytes

In [7]:
orders[orders['customer_id'].isna()]

   order_id customer_id           order_date  amount order_status
11     O111         NaN  2026-10-03 16:00:00    2200    COMPLETED

In [8]:
orders[orders.duplicated()]

  order_id customer_id           order_date  amount order_status
8     O108         C07  2026-10-03 09:00:00    2700    completed

In [9]:
orders.shape

(12, 5)

In [10]:
customers.head()

  customer_id customer_name region           updated_at
0         C01         Aarav   West  2026-09-20 10:00:00
1         C02          Diya  south  2026-09-21 11:00:00
2         C03         Kabir   WEST  2026-09-22 09:00:00
3         C04         Meera  North  2026-09-22 15:00:00
4         C05        Ishaan    NaN  2026-09-23 10:00:00

In [11]:
customers[customers.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_name, region, updated_at]
Index: []

In [12]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    10 non-null     str
 1   customer_name  10 non-null     str
 2   region         9 non-null      str
 3   updated_at     10 non-null     str
dtypes: str(4)
memory usage: 452.0 bytes

In [13]:
customers.shape

(10, 4)

In [14]:
payments.head()

  payment_id order_id payment_status  payment_amount
0       P001     O101        SUCCESS            1200
1       P002     O102        success            2500
2       P003     O103         FAILED             800
3       P004     O104        SUCCESS            4000
4       P005     O105        SUCCESS             500

In [15]:
payments[payments['payment_amount'] < 0]

Empty DataFrame
Columns: [payment_id, order_id, payment_status, payment_amount]
Index: []

In [16]:
payments[payments.duplicated()]

  payment_id order_id payment_status  payment_amount
8       P008     O108        SUCCESS            2700

In [17]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      12 non-null     str
 1   order_id        12 non-null     str
 2   payment_status  12 non-null     str
 3   payment_amount  12 non-null     int64
dtypes: int64(1), str(3)
memory usage: 516.0 bytes

In [18]:
payments.shape

(12, 4)

## Clean

In [19]:
orders['order_status'] = orders['order_status'].str.strip().str.upper()

In [20]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [21]:
customers['region'] = customers['region'].str.strip().str.capitalize()

In [22]:
customers['updated_at'] = pd.to_datetime(customers['updated_at'])

In [23]:
payments['payment_status'] = payments['payment_status'].str.strip().str.upper()

## Validate

In [24]:
valid_orders = orders[
    ~(orders['customer_id'].isna()) & 
    (orders['amount'] > 0) & 
    (orders['order_status'].isin(['COMPLETED', 'CANCELLED']))
]

In [25]:
invalid_orders = orders[~orders['order_id'].isin(valid_orders['order_id'])]

In [26]:
valid_orders

   order_id customer_id          order_date  amount order_status
0      O101         C01 2026-10-01 09:15:00    1200    COMPLETED
1      O102         C02 2026-10-01 10:30:00    2500    COMPLETED
2      O103         C03 2026-10-01 11:00:00     800    COMPLETED
3      O104         C01 2026-10-02 08:45:00    4000    COMPLETED
5      O106         C05 2026-10-02 11:20:00    3200    CANCELLED
6      O107         C06 2026-10-02 14:00:00    1500    COMPLETED
7      O108         C07 2026-10-03 09:00:00    2700    COMPLETED
8      O108         C07 2026-10-03 09:00:00    2700    COMPLETED
10     O110         C09 2026-10-03 14:30:00    1800    COMPLETED

In [27]:
invalid_orders

   order_id customer_id          order_date  amount order_status
4      O105         C04 2026-10-02 09:30:00    -500    COMPLETED
9      O109         C08 2026-10-03 12:00:00    5000      UNKNOWN
11     O111         NaN 2026-10-03 16:00:00    2200    COMPLETED

## Deduplicate

In [28]:
valid_orders[valid_orders.duplicated()]

  order_id customer_id          order_date  amount order_status
8     O108         C07 2026-10-03 09:00:00    2700    COMPLETED

In [29]:
valid_orders.drop_duplicates(inplace=True)

In [30]:
customers[customers.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_name, region, updated_at]
Index: []

In [31]:
sorted_customers = customers.sort_values(by='updated_at', ascending=True)

In [32]:
sorted_customers

  customer_id customer_name region          updated_at
6         C07         Arjun   East 2026-09-20 09:00:00
0         C01         Aarav   West 2026-09-20 10:00:00
1         C02          Diya  South 2026-09-21 11:00:00
2         C03         Kabir   West 2026-09-22 09:00:00
3         C04         Meera  North 2026-09-22 15:00:00
4         C05        Ishaan    NaN 2026-09-23 10:00:00
5         C06          Riya  South 2026-09-24 13:00:00
8         C08          Sara   East 2026-09-25 08:00:00
9         C09        Vivaan  North 2026-09-26 17:00:00
7         C07         Arjun   West 2026-09-29 18:00:00

In [33]:
latest_records = sorted_customers.drop_duplicates(subset=['customer_id'], keep='last')

In [34]:
latest_records

  customer_id customer_name region          updated_at
0         C01         Aarav   West 2026-09-20 10:00:00
1         C02          Diya  South 2026-09-21 11:00:00
2         C03         Kabir   West 2026-09-22 09:00:00
3         C04         Meera  North 2026-09-22 15:00:00
4         C05        Ishaan    NaN 2026-09-23 10:00:00
5         C06          Riya  South 2026-09-24 13:00:00
8         C08          Sara   East 2026-09-25 08:00:00
9         C09        Vivaan  North 2026-09-26 17:00:00
7         C07         Arjun   West 2026-09-29 18:00:00

In [35]:
payments[payments.duplicated()]

  payment_id order_id payment_status  payment_amount
8       P008     O108        SUCCESS            2700

In [36]:
payments[payments['payment_id'] == 'P008']

  payment_id order_id payment_status  payment_amount
7       P008     O108        SUCCESS            2700
8       P008     O108        SUCCESS            2700

In [37]:
payments = payments.drop_duplicates(subset=['payment_id'])

## Reconcile Payments

In [38]:
completed_orders = valid_orders[valid_orders['order_status'] == 'COMPLETED']

In [39]:
completed_orders

   order_id customer_id          order_date  amount order_status
0      O101         C01 2026-10-01 09:15:00    1200    COMPLETED
1      O102         C02 2026-10-01 10:30:00    2500    COMPLETED
2      O103         C03 2026-10-01 11:00:00     800    COMPLETED
3      O104         C01 2026-10-02 08:45:00    4000    COMPLETED
6      O107         C06 2026-10-02 14:00:00    1500    COMPLETED
7      O108         C07 2026-10-03 09:00:00    2700    COMPLETED
10     O110         C09 2026-10-03 14:30:00    1800    COMPLETED

In [40]:
succesful_payments = payments[payments['payment_status'] == 'SUCCESS']

In [41]:
succesful_payments

   payment_id order_id payment_status  payment_amount
0        P001     O101        SUCCESS            1200
1        P002     O102        SUCCESS            2500
3        P004     O104        SUCCESS            4000
4        P005     O105        SUCCESS             500
5        P006     O106        SUCCESS            3200
6        P007     O107        SUCCESS            1500
7        P008     O108        SUCCESS            2700
9        P009     O999        SUCCESS             999
11       P011     O109        SUCCESS            5000

In [42]:
joined = valid_orders.merge(
    payments,
    how='outer',
    on='order_id',
    indicator=True,
    validate='1:1'
)

In [43]:
joined

,order_id,customer_id,order_date,amount,order_status,payment_id,payment_status,payment_amount,_merge
0,O101,C01,2026-10-01 09:15:00,1200.0,COMPLETED,P001,SUCCESS,1200,both
1,O102,C02,2026-10-01 10:30:00,2500.0,COMPLETED,P002,SUCCESS,2500,both
2,O103,C03,2026-10-01 11:00:00,800.0,COMPLETED,P003,FAILED,800,both
3,O104,C01,2026-10-02 08:45:00,4000.0,COMPLETED,P004,SUCCESS,4000,both
4,O105,NaN,NaT,NaN,NaN,P005,SUCCESS,500,right_only
5,O106,C05,2026-10-02 11:20:00,3200.0,CANCELLED,P006,SUCCESS,3200,both
6,O107,C06,2026-10-02 14:00:00,1500.0,COMPLETED,P007,SUCCESS,1500,both
7,O108,C07,2026-10-03 09:00:00,2700.0,COMPLETED,P008,SUCCESS,2700,both
8,O109,NaN,NaT,NaN,NaN,P011,SUCCESS,5000,right_only
9,O110,C09,2026-10-03 14:30:00,1800.0,COMPLETED,P010,FAILED,1800,both
10,O999,NaN,NaT,NaN,NaN,P009,SUCCESS,999,right_only

In [44]:
orphan_successful_payments = joined[(joined['payment_status'] == 'SUCCESS') & (joined['_merge'] == 'right_only')]

In [45]:
orphan_successful_payments

,order_id,customer_id,order_date,amount,order_status,payment_id,payment_status,payment_amount,_merge
4,O105,NaN,NaT,NaN,NaN,P005,SUCCESS,500,right_only
8,O109,NaN,NaT,NaN,NaN,P011,SUCCESS,5000,right_only
10,O999,NaN,NaT,NaN,NaN,P009,SUCCESS,999,right_only

In [46]:
completed_orders_without_successful_payments = joined[
    (joined['order_status'] == 'COMPLETED') & 
    (joined['payment_status'] != 'SUCCESS')
]

In [47]:
completed_orders_without_successful_payments

,order_id,customer_id,order_date,amount,order_status,payment_id,payment_status,payment_amount,_merge
2,O103,C03,2026-10-01 11:00:00,800.0,COMPLETED,P003,FAILED,800,both
9,O110,C09,2026-10-03 14:30:00,1800.0,COMPLETED,P010,FAILED,1800,both

In [48]:
successful_paid_orders = joined[joined['payment_status'] == 'SUCCESS']

In [49]:
successful_paid_orders

,order_id,customer_id,order_date,amount,order_status,payment_id,payment_status,payment_amount,_merge
0,O101,C01,2026-10-01 09:15:00,1200.0,COMPLETED,P001,SUCCESS,1200,both
1,O102,C02,2026-10-01 10:30:00,2500.0,COMPLETED,P002,SUCCESS,2500,both
3,O104,C01,2026-10-02 08:45:00,4000.0,COMPLETED,P004,SUCCESS,4000,both
4,O105,NaN,NaT,NaN,NaN,P005,SUCCESS,500,right_only
5,O106,C05,2026-10-02 11:20:00,3200.0,CANCELLED,P006,SUCCESS,3200,both
6,O107,C06,2026-10-02 14:00:00,1500.0,COMPLETED,P007,SUCCESS,1500,both
7,O108,C07,2026-10-03 09:00:00,2700.0,COMPLETED,P008,SUCCESS,2700,both
8,O109,NaN,NaT,NaN,NaN,P011,SUCCESS,5000,right_only
10,O999,NaN,NaT,NaN,NaN,P009,SUCCESS,999,right_only

In [50]:
completed_orders_with_successful_payments = joined[
    (joined['order_status'] == 'COMPLETED') &
    (joined['payment_status'] == 'SUCCESS')
]

In [51]:
completed_orders_with_successful_payments

,order_id,customer_id,order_date,amount,order_status,payment_id,payment_status,payment_amount,_merge
0,O101,C01,2026-10-01 09:15:00,1200.0,COMPLETED,P001,SUCCESS,1200,both
1,O102,C02,2026-10-01 10:30:00,2500.0,COMPLETED,P002,SUCCESS,2500,both
3,O104,C01,2026-10-02 08:45:00,4000.0,COMPLETED,P004,SUCCESS,4000,both
6,O107,C06,2026-10-02 14:00:00,1500.0,COMPLETED,P007,SUCCESS,1500,both
7,O108,C07,2026-10-03 09:00:00,2700.0,COMPLETED,P008,SUCCESS,2700,both

## Build curated other dataset

In [52]:
df = completed_orders_with_successful_payments.merge(
    latest_records,
    how='inner',
    on='customer_id'
)

In [53]:
df

,order_id,customer_id,order_date,amount,order_status,payment_id,payment_status,payment_amount,_merge,customer_name,region,updated_at
0,O101,C01,2026-10-01 09:15:00,1200.0,COMPLETED,P001,SUCCESS,1200,both,Aarav,West,2026-09-20 10:00:00
1,O102,C02,2026-10-01 10:30:00,2500.0,COMPLETED,P002,SUCCESS,2500,both,Diya,South,2026-09-21 11:00:00
2,O104,C01,2026-10-02 08:45:00,4000.0,COMPLETED,P004,SUCCESS,4000,both,Aarav,West,2026-09-20 10:00:00
3,O107,C06,2026-10-02 14:00:00,1500.0,COMPLETED,P007,SUCCESS,1500,both,Riya,South,2026-09-24 13:00:00
4,O108,C07,2026-10-03 09:00:00,2700.0,COMPLETED,P008,SUCCESS,2700,both,Arjun,West,2026-09-29 18:00:00

In [54]:
df = df.loc[
    :,
    [
        'order_id',
        'order_date',
        'customer_id',
        'customer_name',
        'region',
        'amount',
        'payment_amount'
    ]
]

In [55]:
df

,order_id,order_date,customer_id,customer_name,region,amount,payment_amount
0,O101,2026-10-01 09:15:00,C01,Aarav,West,1200.0,1200
1,O102,2026-10-01 10:30:00,C02,Diya,South,2500.0,2500
2,O104,2026-10-02 08:45:00,C01,Aarav,West,4000.0,4000
3,O107,2026-10-02 14:00:00,C06,Riya,South,1500.0,1500
4,O108,2026-10-03 09:00:00,C07,Arjun,West,2700.0,2700

In [56]:
df['revenue_match'] = df['amount'] == df['payment_amount']

In [57]:
df

,order_id,order_date,customer_id,customer_name,region,amount,payment_amount,revenue_match
0,O101,2026-10-01 09:15:00,C01,Aarav,West,1200.0,1200,True
1,O102,2026-10-01 10:30:00,C02,Diya,South,2500.0,2500,True
2,O104,2026-10-02 08:45:00,C01,Aarav,West,4000.0,4000,True
3,O107,2026-10-02 14:00:00,C06,Riya,South,1500.0,1500,True
4,O108,2026-10-03 09:00:00,C07,Arjun,West,2700.0,2700,True

## Daily regional summary

In [58]:
daily_regional_summary = df.groupby([df['order_date'].dt.date, 'region']).agg(
    successful_orders=('order_id', 'count'),
    unique_customers=('customer_id', 'nunique'),
    total_order_amount=('amount', 'sum'),
    total_payment_amount=('payment_amount', 'sum')
)

In [59]:
daily_regional_summary = daily_regional_summary.sort_values(
    ['order_date', 'region']
)

In [60]:
daily_regional_summary

                   successful_orders  unique_customers  total_order_amount  \
order_date region
2026-10-01 South                   1                 1              2500.0
           West                    1                 1              1200.0
2026-10-02 South                   1                 1              1500.0
           West                    1                 1              4000.0
2026-10-03 West                    1                 1              2700.0

                   total_payment_amount
order_date region
2026-10-01 South                   2500
           West                    1200
2026-10-02 South                   1500
           West                    4000
2026-10-03 West                    2700