In [ ]:
import pandas as pd

In [2]:
sales = pd.DataFrame({
    "region": ["East", "East", "East", "West", "West", "West"],
    "month": ["Jan", "Jan", "Feb", "Jan", "Feb", "Feb"],
    "category": ["Laptop", "Phone", "Laptop", "Laptop", "Phone", "Laptop"],
    "revenue": [50000, 30000, 60000, 40000, 35000, 45000]
})

In [3]:
sales.head()

  region month category  revenue
0   East   Jan   Laptop    50000
1   East   Jan    Phone    30000
2   East   Feb   Laptop    60000
3   West   Jan   Laptop    40000
4   West   Feb    Phone    35000

Create a table with region as rows, month as columns, and total revenue as values.

In [8]:
region_revenue = sales.pivot_table(
    index='region',
    columns='month',
    values='revenue',
    aggfunc='sum'
)

In [9]:
region_revenue

month     Feb    Jan
region
East    60000  80000
West    80000  40000

Create a table with region as rows, category as columns, and total revenue as values.

In [10]:
category_revenue = sales.pivot_table(
    index='region',
    columns='category',
    values='revenue',
    aggfunc='sum'
)

In [11]:
category_revenue

category  Laptop  Phone
region
East      110000  30000
West       85000  35000

Take your result from #1 and use melt() to convert it back toward long format. Keep region as the identifier.

In [15]:
region_revenue.reset_index().melt(
    id_vars='region',
    var_name='month',
    value_name='revenue'
)

  region month  revenue
0   East   Feb    60000
1   West   Feb    80000
2   East   Jan    80000
3   West   Jan    40000

Using groupby(), create total revenue by region + category, then use unstack() to turn category into columns.

In [20]:
grouped = sales.groupby(['region', 'category']).agg(
    total_revenue=('revenue', 'sum')
)

In [21]:
grouped

                 total_revenue
region category
East   Laptop           110000
       Phone             30000
West   Laptop            85000
       Phone             35000

In [22]:
grouped.unstack()

         total_revenue
category        Laptop  Phone
region
East            110000  30000
West             85000  35000