In [1]:
import pandas as pd

In [2]:
data = {
    "Txn_ID": ["T101", "T102", "T102", "T103", "T104"],
    "Customer_ID": [101, 102, 102, None, 104],
    "Amount": ["500.0", "750.0", "750.0", "1200.0", "300.0"],
    "Status": [" success ", "FAILED", "FAILED", None, " Success"]
}

In [3]:
df = pd.DataFrame(data)

Investigation

In [4]:
df.head()

  Txn_ID  Customer_ID  Amount     Status
0   T101        101.0   500.0   success
1   T102        102.0   750.0     FAILED
2   T102        102.0   750.0     FAILED
3   T103          NaN  1200.0        NaN
4   T104        104.0   300.0    Success

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Txn_ID       5 non-null      str
 1   Customer_ID  4 non-null      float64
 2   Amount       5 non-null      str
 3   Status       4 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

Find the number of null values in every column.

In [6]:
df.isna().sum()

Txn_ID         0
Customer_ID    1
Amount         0
Status         1
dtype: int64

Find duplicate transactions based on Txn_ID.

In [7]:
df[df.duplicated(subset=['Txn_ID'])]

  Txn_ID  Customer_ID Amount  Status
2   T102        102.0  750.0  FAILED

Remove the duplicate T102.

In [8]:
df.drop_duplicates(subset=['Txn_ID'], inplace=True)

In [9]:
df

  Txn_ID  Customer_ID  Amount     Status
0   T101        101.0   500.0   success
1   T102        102.0   750.0     FAILED
3   T103          NaN  1200.0        NaN
4   T104        104.0   300.0    Success

Rename Txn_ID → transaction_id

In [10]:
df.rename(columns={
    'Txn_ID': 'transaction_id'
}, inplace=True)

In [11]:
df

  transaction_id  Customer_ID  Amount     Status
0           T101        101.0   500.0   success
1           T102        102.0   750.0     FAILED
3           T103          NaN  1200.0        NaN
4           T104        104.0   300.0    Success

Convert Amount to float

In [12]:
df['Amount'] = df['Amount'].astype("float64")

Standardize Status so values such as " success " and " Success" become "SUCCESS"

In [13]:
df['Status'] = df['Status'].str.strip().str.upper()

Replace missing status values with "UNKNOWN".

In [14]:
df['Status'] = df['Status'].fillna(value="UNKNOWN")

In [15]:
df

  transaction_id  Customer_ID  Amount   Status
0           T101        101.0   500.0  SUCCESS
1           T102        102.0   750.0   FAILED
3           T103          NaN  1200.0  UNKNOWN
4           T104        104.0   300.0  SUCCESS

Remove records where Customer_ID is missing

In [16]:
df.dropna(subset=["Customer_ID"], inplace=True)

In [17]:
df

  transaction_id  Customer_ID  Amount   Status
0           T101        101.0   500.0  SUCCESS
1           T102        102.0   750.0   FAILED
4           T104        104.0   300.0  SUCCESS

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 0 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  3 non-null      str
 1   Customer_ID     3 non-null      float64
 2   Amount          3 non-null      float64
 3   Status          3 non-null      str
dtypes: float64(2), str(2)
memory usage: 120.0 bytes

How many rows remain? -> 3 \
How many nulls remain? -> 0 \
How many duplicate transaction IDs remain? -> 0 \
What are the dtypes? -> transaction_id = str, Customer_ID = float64, Amount = float64, Status = str