In [1]:
import pandas as pd
import numpy as np

In [2]:
# ============================================================
# INPUT 1: EXISTING CUSTOMER TARGET
# ============================================================

customer_target = pd.DataFrame({
    "customer_id": [
        "C101", "C102", "C103", "C104", "C105"
    ],
    "customer_name": [
        "Amit Sharma",
        "Neha Patil",
        "Rahul Verma",
        "Sneha Iyer",
        "Karan Shah"
    ],
    "region": [
        "West", "West", "North", "South", "West"
    ],
    "customer_tier": [
        "Gold", "Silver", "Gold", "Bronze", "Silver"
    ],
    "updated_at": [
        "2026-09-20 10:00:00",
        "2026-09-21 09:30:00",
        "2026-09-19 14:00:00",
        "2026-09-22 11:00:00",
        "2026-09-20 16:30:00"
    ]
})


# ============================================================
# INPUT 2: TODAY'S CUSTOMER CDC BATCH
# ============================================================

customer_batch = pd.DataFrame({
    "customer_id": [
        "C102", "C103", "C106", "C107", "C102",
        "C106", "C108", "C109", "C107"
    ],
    "customer_name": [
        "Neha Patil",
        "Rahul Verma",
        "Priya Nair",
        "Arjun Mehta",
        "Neha Patil",
        "Priya Nair",
        "Meera Joshi",
        np.nan,
        "Arjun Mehta"
    ],
    "region": [
        "West",
        "North",
        "South",
        "WEST",
        "West",
        "South",
        np.nan,
        "North",
        "West"
    ],
    "customer_tier": [
        "Gold",
        "Gold",
        "Silver",
        "Bronze",
        "Platinum",
        "Gold",
        "Silver",
        "Bronze",
        "Bronze"
    ],
    "updated_at": [
        "2026-09-28 08:00:00",
        "2026-09-28 08:30:00",
        "2026-09-28 09:00:00",
        "2026-09-28 09:15:00",
        "2026-09-28 10:00:00",
        "2026-09-28 10:30:00",
        "2026-09-28 11:00:00",
        "2026-09-28 11:15:00",
        "2026-09-28 09:15:00"
    ]
})


# ============================================================
# INPUT 3: TODAY'S ORDERS BATCH
# ============================================================

orders_batch = pd.DataFrame({
    "order_id": [
        "O5001", "O5002", "O5003", "O5004", "O5005",
        "O5006", "O5007", "O5008", "O5002", "O5009",
        "O5010"
    ],
    "customer_id": [
        "C101", "C102", "C106", "C107", "C999",
        "C103", "C106", "C105", "C102", "C101",
        "C108"
    ],
    "order_ts": [
        "2026-09-28 08:10:00",
        "2026-09-28 09:00:00",
        "2026-09-28 09:20:00",
        "2026-09-28 10:00:00",
        "2026-09-28 10:30:00",
        "2026-09-28 11:00:00",
        "2026-09-28 12:00:00",
        "2026-09-28 13:00:00",
        "2026-09-28 09:00:00",
        "2026-09-28 14:00:00",
        "2026-09-28 15:00:00"
    ],
    "category": [
        "Electronics",
        "Fashion",
        "Electronics",
        "Grocery",
        "Fashion",
        "Electronics",
        "Fashion",
        "Grocery",
        "Fashion",
        "Electronics",
        "Grocery"
    ],
    "amount": [
        25000,
        4500,
        18000,
        2200,
        5000,
        -1000,
        np.nan,
        1500,
        4500,
        12000,
        3200
    ],
    "status": [
        "completed",
        "COMPLETED",
        "Completed",
        "completed",
        "completed",
        "completed",
        "completed",
        "cancelled",
        "COMPLETED",
        "completed",
        "completed"
    ]
})

### Part A - Inspect & Validate

In [3]:
customer_batch.head()

  customer_id customer_name region customer_tier           updated_at
0        C102    Neha Patil   West          Gold  2026-09-28 08:00:00
1        C103   Rahul Verma  North          Gold  2026-09-28 08:30:00
2        C106    Priya Nair  South        Silver  2026-09-28 09:00:00
3        C107   Arjun Mehta   WEST        Bronze  2026-09-28 09:15:00
4        C102    Neha Patil   West      Platinum  2026-09-28 10:00:00

In [4]:
customer_batch['region'].value_counts()

region
West     3
North    2
South    2
WEST     1
Name: count, dtype: int64

In [5]:
customer_batch['customer_tier'].value_counts()

customer_tier
Gold        3
Bronze      3
Silver      2
Platinum    1
Name: count, dtype: int64

- West is duplicated due to spelling mismatch

In [6]:
customer_batch.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    9 non-null      str
 1   customer_name  8 non-null      str
 2   region         8 non-null      str
 3   customer_tier  9 non-null      str
 4   updated_at     9 non-null      str
dtypes: str(5)
memory usage: 492.0 bytes

- Need to change updated at to datatime

In [7]:
customer_batch.columns == customer_target.columns

array([ True,  True,  True,  True,  True])

In [8]:
customer_batch.shape

(9, 5)

In [9]:
customer_target.head()

  customer_id customer_name region customer_tier           updated_at
0        C101   Amit Sharma   West          Gold  2026-09-20 10:00:00
1        C102    Neha Patil   West        Silver  2026-09-21 09:30:00
2        C103   Rahul Verma  North          Gold  2026-09-19 14:00:00
3        C104    Sneha Iyer  South        Bronze  2026-09-22 11:00:00
4        C105    Karan Shah   West        Silver  2026-09-20 16:30:00

In [10]:
customer_target['region'].value_counts()

region
West     3
North    1
South    1
Name: count, dtype: int64

In [11]:
customer_target['customer_tier'].value_counts()

customer_tier
Gold      2
Silver    2
Bronze    1
Name: count, dtype: int64

In [12]:
customer_target.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      str
 1   customer_name  5 non-null      str
 2   region         5 non-null      str
 3   customer_tier  5 non-null      str
 4   updated_at     5 non-null      str
dtypes: str(5)
memory usage: 332.0 bytes

- Need to change updated at to datatime

In [13]:
customer_target.shape

(5, 5)

In [14]:
orders_batch.head()

  order_id customer_id             order_ts     category   amount     status
0    O5001        C101  2026-09-28 08:10:00  Electronics  25000.0  completed
1    O5002        C102  2026-09-28 09:00:00      Fashion   4500.0  COMPLETED
2    O5003        C106  2026-09-28 09:20:00  Electronics  18000.0  Completed
3    O5004        C107  2026-09-28 10:00:00      Grocery   2200.0  completed
4    O5005        C999  2026-09-28 10:30:00      Fashion   5000.0  completed

In [15]:
orders_batch['category'].value_counts()

category
Electronics    4
Fashion        4
Grocery        3
Name: count, dtype: int64

In [16]:
orders_batch['status'].value_counts()

status
completed    7
COMPLETED    2
Completed    1
cancelled    1
Name: count, dtype: int64

- Completed needs to be corrected

In [17]:
orders_batch.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     11 non-null     str
 1   customer_id  11 non-null     str
 2   order_ts     11 non-null     str
 3   category     11 non-null     str
 4   amount       10 non-null     float64
 5   status       11 non-null     str
dtypes: float64(1), str(5)
memory usage: 660.0 bytes

- Need to change order_ts to datatime

In [18]:
orders_batch.shape

(11, 6)

### Part B - Clean today's customer batch

In [19]:
customer_target.head()

  customer_id customer_name region customer_tier           updated_at
0        C101   Amit Sharma   West          Gold  2026-09-20 10:00:00
1        C102    Neha Patil   West        Silver  2026-09-21 09:30:00
2        C103   Rahul Verma  North          Gold  2026-09-19 14:00:00
3        C104    Sneha Iyer  South        Bronze  2026-09-22 11:00:00
4        C105    Karan Shah   West        Silver  2026-09-20 16:30:00

In [20]:
customer_batch

  customer_id customer_name region customer_tier           updated_at
0        C102    Neha Patil   West          Gold  2026-09-28 08:00:00
1        C103   Rahul Verma  North          Gold  2026-09-28 08:30:00
2        C106    Priya Nair  South        Silver  2026-09-28 09:00:00
3        C107   Arjun Mehta   WEST        Bronze  2026-09-28 09:15:00
4        C102    Neha Patil   West      Platinum  2026-09-28 10:00:00
5        C106    Priya Nair  South          Gold  2026-09-28 10:30:00
6        C108   Meera Joshi    NaN        Silver  2026-09-28 11:00:00
7        C109           NaN  North        Bronze  2026-09-28 11:15:00
8        C107   Arjun Mehta   West        Bronze  2026-09-28 09:15:00

In [21]:
cleaned = customer_batch[~((customer_batch['customer_id'].isna()) | (customer_batch['customer_name'].isna()))]

In [22]:
cleaned['region'] = cleaned['region'].fillna('Unknown')

In [23]:
cleaned['region'] = cleaned['region'].str.strip().str.capitalize()

In [24]:
cleaned['updated_at'] = pd.to_datetime(cleaned['updated_at'])

In [25]:
cleaned[cleaned.duplicated()]

  customer_id customer_name region customer_tier          updated_at
8        C107   Arjun Mehta   West        Bronze 2026-09-28 09:15:00

In [26]:
cleaned = cleaned.drop_duplicates()

In [27]:
cleaned

  customer_id customer_name   region customer_tier          updated_at
0        C102    Neha Patil     West          Gold 2026-09-28 08:00:00
1        C103   Rahul Verma    North          Gold 2026-09-28 08:30:00
2        C106    Priya Nair    South        Silver 2026-09-28 09:00:00
3        C107   Arjun Mehta     West        Bronze 2026-09-28 09:15:00
4        C102    Neha Patil     West      Platinum 2026-09-28 10:00:00
5        C106    Priya Nair    South          Gold 2026-09-28 10:30:00
6        C108   Meera Joshi  Unknown        Silver 2026-09-28 11:00:00

In [28]:
cleaned = cleaned.sort_values(
    by=['updated_at']
).drop_duplicates(
    subset=['customer_id'],
    keep='last'
)

In [29]:
cleaned

  customer_id customer_name   region customer_tier          updated_at
1        C103   Rahul Verma    North          Gold 2026-09-28 08:30:00
3        C107   Arjun Mehta     West        Bronze 2026-09-28 09:15:00
4        C102    Neha Patil     West      Platinum 2026-09-28 10:00:00
5        C106    Priya Nair    South          Gold 2026-09-28 10:30:00
6        C108   Meera Joshi  Unknown        Silver 2026-09-28 11:00:00

### Part C - Incrementally refresh the customer target

In [30]:
customer_target

  customer_id customer_name region customer_tier           updated_at
0        C101   Amit Sharma   West          Gold  2026-09-20 10:00:00
1        C102    Neha Patil   West        Silver  2026-09-21 09:30:00
2        C103   Rahul Verma  North          Gold  2026-09-19 14:00:00
3        C104    Sneha Iyer  South        Bronze  2026-09-22 11:00:00
4        C105    Karan Shah   West        Silver  2026-09-20 16:30:00

In [31]:
customer_target['updated_at'] = pd.to_datetime(customer_target['updated_at'])

In [32]:
joined = cleaned.merge(
    customer_target,
    on='customer_id',
    how='left',
    indicator=True,
)

In [33]:
new_customers = joined[joined['_merge'] == 'left_only']['customer_id']

In [34]:
existing_customers = joined[joined['_merge'] == 'both']['customer_id']

In [35]:
print(f'New Customers: \n{new_customers}')
print(f'Existing Customers: \n{existing_customers}')

New Customers:
1    C107
3    C106
4    C108
Name: customer_id, dtype: str
Existing Customers:
0    C103
2    C102
Name: customer_id, dtype: str

In [36]:
customer_target = pd.concat([customer_target, cleaned], ignore_index=True).sort_values(by=['updated_at']).drop_duplicates(subset=['customer_id'], keep='last')

In [37]:
customer_target

  customer_id customer_name   region customer_tier          updated_at
0        C101   Amit Sharma     West          Gold 2026-09-20 10:00:00
4        C105    Karan Shah     West        Silver 2026-09-20 16:30:00
3        C104    Sneha Iyer    South        Bronze 2026-09-22 11:00:00
5        C103   Rahul Verma    North          Gold 2026-09-28 08:30:00
6        C107   Arjun Mehta     West        Bronze 2026-09-28 09:15:00
7        C102    Neha Patil     West      Platinum 2026-09-28 10:00:00
8        C106    Priya Nair    South          Gold 2026-09-28 10:30:00
9        C108   Meera Joshi  Unknown        Silver 2026-09-28 11:00:00

- This operation is idempotent. Even if ran multiple times, result would be same

### Part D - Clean Orders

In [38]:
orders_batch.head()

  order_id customer_id             order_ts     category   amount     status
0    O5001        C101  2026-09-28 08:10:00  Electronics  25000.0  completed
1    O5002        C102  2026-09-28 09:00:00      Fashion   4500.0  COMPLETED
2    O5003        C106  2026-09-28 09:20:00  Electronics  18000.0  Completed
3    O5004        C107  2026-09-28 10:00:00      Grocery   2200.0  completed
4    O5005        C999  2026-09-28 10:30:00      Fashion   5000.0  completed

In [39]:
orders_batch[orders_batch.duplicated()]

  order_id customer_id             order_ts category  amount     status
8    O5002        C102  2026-09-28 09:00:00  Fashion  4500.0  COMPLETED

In [40]:
orders_batch = orders_batch.drop_duplicates()

In [41]:
orders_batch

   order_id customer_id             order_ts     category   amount     status
0     O5001        C101  2026-09-28 08:10:00  Electronics  25000.0  completed
1     O5002        C102  2026-09-28 09:00:00      Fashion   4500.0  COMPLETED
2     O5003        C106  2026-09-28 09:20:00  Electronics  18000.0  Completed
3     O5004        C107  2026-09-28 10:00:00      Grocery   2200.0  completed
4     O5005        C999  2026-09-28 10:30:00      Fashion   5000.0  completed
5     O5006        C103  2026-09-28 11:00:00  Electronics  -1000.0  completed
6     O5007        C106  2026-09-28 12:00:00      Fashion      NaN  completed
7     O5008        C105  2026-09-28 13:00:00      Grocery   1500.0  cancelled
9     O5009        C101  2026-09-28 14:00:00  Electronics  12000.0  completed
10    O5010        C108  2026-09-28 15:00:00      Grocery   3200.0  completed

In [42]:
cleaned_orders_batch = orders_batch[~((orders_batch['order_id'].isna() )| (orders_batch['customer_id'].isna()))]

In [43]:
cleaned_orders_batch['order_ts'] = pd.to_datetime(cleaned_orders_batch['order_ts'])

In [44]:
cleaned_orders_batch['status'] = cleaned_orders_batch['status'].str.strip().str.capitalize()

In [45]:
cleaned_orders_batch.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 0 to 10
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     10 non-null     str
 1   customer_id  10 non-null     str
 2   order_ts     10 non-null     datetime64[us]
 3   category     10 non-null     str
 4   amount       9 non-null      float64
 5   status       10 non-null     str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 560.0 bytes

In [46]:
cleaned_orders_batch['amount'] = pd.to_numeric(cleaned_orders_batch['amount'])

In [47]:
valid_orders = cleaned_orders_batch[~((cleaned_orders_batch['amount'].isna()) | (cleaned_orders_batch['amount'] <= 0))]

In [48]:
invalid_orders = cleaned_orders_batch[(cleaned_orders_batch['amount'].isna()) | (cleaned_orders_batch['amount'] <= 0)]

In [49]:
valid_orders

   order_id customer_id            order_ts     category   amount     status
0     O5001        C101 2026-09-28 08:10:00  Electronics  25000.0  Completed
1     O5002        C102 2026-09-28 09:00:00      Fashion   4500.0  Completed
2     O5003        C106 2026-09-28 09:20:00  Electronics  18000.0  Completed
3     O5004        C107 2026-09-28 10:00:00      Grocery   2200.0  Completed
4     O5005        C999 2026-09-28 10:30:00      Fashion   5000.0  Completed
7     O5008        C105 2026-09-28 13:00:00      Grocery   1500.0  Cancelled
9     O5009        C101 2026-09-28 14:00:00  Electronics  12000.0  Completed
10    O5010        C108 2026-09-28 15:00:00      Grocery   3200.0  Completed

In [50]:
completed_valid_orders = valid_orders[valid_orders['status'] == 'Completed']

In [51]:
invalid_orders

  order_id customer_id            order_ts     category  amount     status
5    O5006        C103 2026-09-28 11:00:00  Electronics -1000.0  Completed
6    O5007        C106 2026-09-28 12:00:00      Fashion     NaN  Completed

### Part E - Customer Reconciliation

In [52]:
completed_valid_orders

   order_id customer_id            order_ts     category   amount     status
0     O5001        C101 2026-09-28 08:10:00  Electronics  25000.0  Completed
1     O5002        C102 2026-09-28 09:00:00      Fashion   4500.0  Completed
2     O5003        C106 2026-09-28 09:20:00  Electronics  18000.0  Completed
3     O5004        C107 2026-09-28 10:00:00      Grocery   2200.0  Completed
4     O5005        C999 2026-09-28 10:30:00      Fashion   5000.0  Completed
9     O5009        C101 2026-09-28 14:00:00  Electronics  12000.0  Completed
10    O5010        C108 2026-09-28 15:00:00      Grocery   3200.0  Completed

In [53]:
customer_target

  customer_id customer_name   region customer_tier          updated_at
0        C101   Amit Sharma     West          Gold 2026-09-20 10:00:00
4        C105    Karan Shah     West        Silver 2026-09-20 16:30:00
3        C104    Sneha Iyer    South        Bronze 2026-09-22 11:00:00
5        C103   Rahul Verma    North          Gold 2026-09-28 08:30:00
6        C107   Arjun Mehta     West        Bronze 2026-09-28 09:15:00
7        C102    Neha Patil     West      Platinum 2026-09-28 10:00:00
8        C106    Priya Nair    South          Gold 2026-09-28 10:30:00
9        C108   Meera Joshi  Unknown        Silver 2026-09-28 11:00:00

In [54]:
joined = completed_valid_orders.merge(
    customer_target,
    how='left',
    on='customer_id',
    indicator=True,
    validate='m:1'
)

In [55]:
joined

,order_id,customer_id,order_ts,category,amount,status,customer_name,region,customer_tier,updated_at,_merge
0,O5001,C101,2026-09-28 08:10:00,Electronics,25000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both
1,O5002,C102,2026-09-28 09:00:00,Fashion,4500.0,Completed,Neha Patil,West,Platinum,2026-09-28 10:00:00,both
2,O5003,C106,2026-09-28 09:20:00,Electronics,18000.0,Completed,Priya Nair,South,Gold,2026-09-28 10:30:00,both
3,O5004,C107,2026-09-28 10:00:00,Grocery,2200.0,Completed,Arjun Mehta,West,Bronze,2026-09-28 09:15:00,both
4,O5005,C999,2026-09-28 10:30:00,Fashion,5000.0,Completed,NaN,NaN,NaN,NaT,left_only
5,O5009,C101,2026-09-28 14:00:00,Electronics,12000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both
6,O5010,C108,2026-09-28 15:00:00,Grocery,3200.0,Completed,Meera Joshi,Unknown,Silver,2026-09-28 11:00:00,both

In [56]:
orphan_orders = joined[joined['_merge'] == 'left_only']

### Part F - Derived Columns

In [57]:
joined

,order_id,customer_id,order_ts,category,amount,status,customer_name,region,customer_tier,updated_at,_merge
0,O5001,C101,2026-09-28 08:10:00,Electronics,25000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both
1,O5002,C102,2026-09-28 09:00:00,Fashion,4500.0,Completed,Neha Patil,West,Platinum,2026-09-28 10:00:00,both
2,O5003,C106,2026-09-28 09:20:00,Electronics,18000.0,Completed,Priya Nair,South,Gold,2026-09-28 10:30:00,both
3,O5004,C107,2026-09-28 10:00:00,Grocery,2200.0,Completed,Arjun Mehta,West,Bronze,2026-09-28 09:15:00,both
4,O5005,C999,2026-09-28 10:30:00,Fashion,5000.0,Completed,NaN,NaN,NaN,NaT,left_only
5,O5009,C101,2026-09-28 14:00:00,Electronics,12000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both
6,O5010,C108,2026-09-28 15:00:00,Grocery,3200.0,Completed,Meera Joshi,Unknown,Silver,2026-09-28 11:00:00,both

In [58]:
joined = joined[joined['_merge'] != 'left_only']

In [59]:
joined['order_date'] = joined['order_ts'].dt.date

In [60]:
joined

,order_id,customer_id,order_ts,category,amount,status,customer_name,region,customer_tier,updated_at,_merge,order_date
0,O5001,C101,2026-09-28 08:10:00,Electronics,25000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both,2026-09-28
1,O5002,C102,2026-09-28 09:00:00,Fashion,4500.0,Completed,Neha Patil,West,Platinum,2026-09-28 10:00:00,both,2026-09-28
2,O5003,C106,2026-09-28 09:20:00,Electronics,18000.0,Completed,Priya Nair,South,Gold,2026-09-28 10:30:00,both,2026-09-28
3,O5004,C107,2026-09-28 10:00:00,Grocery,2200.0,Completed,Arjun Mehta,West,Bronze,2026-09-28 09:15:00,both,2026-09-28
5,O5009,C101,2026-09-28 14:00:00,Electronics,12000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both,2026-09-28
6,O5010,C108,2026-09-28 15:00:00,Grocery,3200.0,Completed,Meera Joshi,Unknown,Silver,2026-09-28 11:00:00,both,2026-09-28

In [ ]:
def get_order_size(amount):
    if amount >= 15000:
        return 'High'
    elif amount >= 5000 and amount < 15000:
        return 'Medium'
    elif amount < 5000:
        return 'Low'

joined['order_size'] = joined['amount'].apply(get_order_size)

In [62]:
joined

,order_id,customer_id,order_ts,category,amount,status,customer_name,region,customer_tier,updated_at,_merge,order_date,order_size
0,O5001,C101,2026-09-28 08:10:00,Electronics,25000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both,2026-09-28,High
1,O5002,C102,2026-09-28 09:00:00,Fashion,4500.0,Completed,Neha Patil,West,Platinum,2026-09-28 10:00:00,both,2026-09-28,low
2,O5003,C106,2026-09-28 09:20:00,Electronics,18000.0,Completed,Priya Nair,South,Gold,2026-09-28 10:30:00,both,2026-09-28,High
3,O5004,C107,2026-09-28 10:00:00,Grocery,2200.0,Completed,Arjun Mehta,West,Bronze,2026-09-28 09:15:00,both,2026-09-28,low
5,O5009,C101,2026-09-28 14:00:00,Electronics,12000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both,2026-09-28,Medium
6,O5010,C108,2026-09-28 15:00:00,Grocery,3200.0,Completed,Meera Joshi,Unknown,Silver,2026-09-28 11:00:00,both,2026-09-28,low

### Part G - Regional KPI Table

In [63]:
regional_kpi = joined.groupby('region').agg(
    total_orders=('order_id', 'count'),
    unique_customers=('customer_id', 'nunique'),
    total_revenue=('amount', 'sum'),
    avg_order_value=('amount', 'mean'),
    max_order_value=('amount', 'max')
)

In [64]:
regional_kpi

,total_orders,unique_customers,total_revenue,avg_order_value,max_order_value
region,,,,,
South,1,1,18000.0,18000.0,18000.0
Unknown,1,1,3200.0,3200.0,3200.0
West,4,3,43700.0,10925.0,25000.0

In [69]:
regional_kpi = regional_kpi.sort_values(by='total_revenue', ascending=False)

In [70]:
regional_kpi

,total_orders,unique_customers,total_revenue,avg_order_value,max_order_value
region,,,,,
West,4,3,43700.0,10925.0,25000.0
South,1,1,18000.0,18000.0,18000.0
Unknown,1,1,3200.0,3200.0,3200.0

### Part H - Customer Level Analytics

In [71]:
customer_analytics = joined.groupby(['customer_id', 'customer_name', 'region']).agg(
    total_orders=('order_id', 'count'),
    total_spend=('amount', 'sum'),
    avg_order_value=('amount', 'mean')
)

In [72]:
customer_analytics

                                   total_orders  total_spend  avg_order_value
customer_id customer_name region
C101        Amit Sharma   West                2      37000.0          18500.0
C102        Neha Patil    West                1       4500.0           4500.0
C106        Priya Nair    South               1      18000.0          18000.0
C107        Arjun Mehta   West                1       2200.0           2200.0
C108        Meera Joshi   Unknown             1       3200.0           3200.0

In [74]:
customer_analytics["regional_avg_customer_spend"] = customer_analytics.groupby('region')['total_spend'].transform('mean')

In [75]:
customer_analytics

,,,total_orders,total_spend,avg_order_value,regional_avg_customer_spend
customer_id,customer_name,region,,,,
C101,Amit Sharma,West,2,37000.0,18500.0,14566.666667
C102,Neha Patil,West,1,4500.0,4500.0,14566.666667
C106,Priya Nair,South,1,18000.0,18000.0,18000.000000
C107,Arjun Mehta,West,1,2200.0,2200.0,14566.666667
C108,Meera Joshi,Unknown,1,3200.0,3200.0,3200.000000

In [77]:
customer_analytics['spend_vs_regional_avg'] = customer_analytics['total_spend'] - customer_analytics['regional_avg_customer_spend']

In [78]:
customer_analytics

,,,total_orders,total_spend,avg_order_value,regional_avg_customer_spend,spend_vs_regional_avg
customer_id,customer_name,region,,,,,
C101,Amit Sharma,West,2,37000.0,18500.0,14566.666667,22433.333333
C102,Neha Patil,West,1,4500.0,4500.0,14566.666667,-10066.666667
C106,Priya Nair,South,1,18000.0,18000.0,18000.000000,0.000000
C107,Arjun Mehta,West,1,2200.0,2200.0,14566.666667,-12366.666667
C108,Meera Joshi,Unknown,1,3200.0,3200.0,3200.000000,0.000000

### Part I - Order Sequence Analysis

In [80]:
sorted_joined = joined.sort_values(['customer_id', 'order_ts'])

In [84]:
sorted_joined['previous_order_amount'] = sorted_joined.groupby('customer_id')['amount'].shift(1)

In [87]:
sorted_joined['amount_change'] = sorted_joined.groupby('customer_id')['amount'].diff()

In [89]:
sorted_joined['cumulative_spend'] = sorted_joined.groupby('customer_id')['amount'].cumsum()

In [90]:
sorted_joined

,order_id,customer_id,order_ts,category,amount,status,customer_name,region,customer_tier,updated_at,_merge,order_date,order_size,previous_order_amount,amount_change,cumulative_spend
0,O5001,C101,2026-09-28 08:10:00,Electronics,25000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both,2026-09-28,High,NaN,NaN,25000.0
5,O5009,C101,2026-09-28 14:00:00,Electronics,12000.0,Completed,Amit Sharma,West,Gold,2026-09-20 10:00:00,both,2026-09-28,Medium,25000.0,-13000.0,37000.0
1,O5002,C102,2026-09-28 09:00:00,Fashion,4500.0,Completed,Neha Patil,West,Platinum,2026-09-28 10:00:00,both,2026-09-28,low,NaN,NaN,4500.0
2,O5003,C106,2026-09-28 09:20:00,Electronics,18000.0,Completed,Priya Nair,South,Gold,2026-09-28 10:30:00,both,2026-09-28,High,NaN,NaN,18000.0
3,O5004,C107,2026-09-28 10:00:00,Grocery,2200.0,Completed,Arjun Mehta,West,Bronze,2026-09-28 09:15:00,both,2026-09-28,low,NaN,NaN,2200.0
6,O5010,C108,2026-09-28 15:00:00,Grocery,3200.0,Completed,Meera Joshi,Unknown,Silver,2026-09-28 11:00:00,both,2026-09-28,low,NaN,NaN,3200.0