In [1]:
import pandas as pd

Exercise 1 - Concat

In [2]:
old = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "city": ["Pune", "Mumbai", "Delhi"]
})

new = pd.DataFrame({
    "customer_id": [104, 105],
    "city": ["Chennai", "Bengaluru"]
})

In [4]:
pd.concat([old, new], ignore_index=True)

   customer_id       city
0          101       Pune
1          102     Mumbai
2          103      Delhi
3          104    Chennai
4          105  Bengaluru

Exercise 2 — Schema drift

In [5]:
target = pd.DataFrame({
    "customer_id": [101, 102],
    "city": ["Pune", "Mumbai"]
})

batch = pd.DataFrame({
    "customer_id": [103],
    "customer_city": ["Delhi"]
})

What do you expect pd.concat([target, batch]) to produce, and why is this dangerous in an ETL pipeline? \
-> Create a new column for customer_city as column names are mismatching

In [7]:
pd.concat([target, batch], ignore_index=True)

   customer_id    city customer_city
0          101    Pune           NaN
1          102  Mumbai           NaN
2          103     NaN         Delhi

Exercise 3 — Anti-join

In [8]:
target = pd.DataFrame({
    "order_id": [1001, 1002, 1003],
})

batch = pd.DataFrame({
    "order_id": [1002, 1004, 1005],
})

In [12]:
joined = batch.merge(
    target,
    how='left',
    on='order_id',
    indicator=True
)

In [13]:
joined[joined['_merge'] == 'left_only']

   order_id     _merge
1      1004  left_only
2      1005  left_only